name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd
            rm -rf MySaskProject
            git clone git@github.com:DhavalPatil1/MySaskProject.git
            cd MySaskProject

            FRONTEND_CONTAINER_ID=$(sudo docker ps -aqf "name=frontend")
            if [ ! -z "$FRONTEND_CONTAINER_ID" ]; then
              sudo docker container stop $FRONTEND_CONTAINER_ID
              sudo docker container rm $FRONTEND_CONTAINER_ID
            fi
            sudo docker-compose -f docker-compose.prod.yml up -d --build
